[project]
name = "mylib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dash>=4.2.0",
    "dash-bootstrap-components>=2.0.4",
    "matplotlib>=3.11.0",
    "numpy>=2.4.6",
    "panda3d>=1.10.16",
    "plotly>=6.8.0",
    "pyopengl>=3.1.10",
    "pyqtgraph>=0.14.0",
    "pyside6>=6.11.1",
    "scipy>=1.17.1",
    "streamlit>=1.58.0",
    "yfinance==0.2.51",
]
